version: '2'

volumes:
  dbdata:
  dbconfig:
  appdb:
  assets:
  distassets:
  extras:

networks:
  backend:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=agnai
      - INITIAL_USER=admin
      - INITIAL_PASSWORD=password
      - JWT_SECRET=self-hosting
      # Optional: Default Agnaistic Subscriber API credentials
      # - AGNAI_SUBSCRIBER_API_URL=https://api.agnai.chat/v1
      # - AGNAI_SUBSCRIBER_API_KEY=your_default_api_key_here
      # - AGNAI_SUBSCRIBER_DEFAULT_PRESET_ID=your_default_preset_id_here
    volumes:
      - appdb:/app/db
      - assets:/app/assets
      - distassets:/app/dist/assets
      - extras:/app/extras
    networks:
      - backend

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - dbdata:/data/db
      - dbconfig:/data/configdb
    networks:
      - backend